//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.UI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Day
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Day()
        {
            this.DayShifts = new HashSet<DayShift>();
        }
    
        public int Id { get; set; }
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        [Display(Name = "Opener")]
        public int OpeningShift { get; set; }
        [Display(Name = "Morning 1")]
        public int MorningShift1 { get; set; }
        [Display(Name = "Morning 2")]
        public int MorningShift2 { get; set; }
        [Display(Name = "Lunch 1")]
        public int LunchShift1 { get; set; }
        [Display(Name = "Lunch 2")]
        public int LunchShift2 { get; set; }
        [Display(Name = "Afternoon 1")]
        public int AfternoonShift1 { get; set; }
        [Display(Name = "Afternoon 2")]
        public int AfternoonShift2 { get; set; }
        [Display(Name = "Closer")]
        public int ClosingShift { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayShift> DayShifts { get; set; }
    }
}
